/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/60U4UxYzYkm
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "~/components/ui/input";
import { Textarea } from "~/components/ui/textarea";
import Image from "next/image";
import { scrollToTop, scrollToBottom } from "../ui/scroll";
import {
  PythonLogo,
  CppLogo,
  TypescriptLogo,
  FullscreenIcon,
  ReactLogo,
  JavascriptLogo,
  WebpageIcon,
  TailwindLogo,
  NumpyLogo,
  GithubLogo,
  LinuxLogo,
  VisualStudioLogo,
  GitLogo,
  NextjsLogo,
  DatabaseIcon,
  CodepenIcon,
  CodeIcon,
  ApiIcon,
} from "../ui/icons";

export function Component() {
  return (
    <div className="flex min-h-[100dvh] flex-col">
      <main className="flex-1">
        <section id="hero" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-6">
                <div className="space-y-4">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Andrew Hoblit
                  </h1>
                  <p className="max-w-[700px] text-muted-foreground md:text-xl lg:text-2xl">
                    Software Developer
                  </p>
                  <p className="md:text-m lg:text-l max-w-[700px] text-muted-foreground">
                    Bachelors of Computer Science, graduated Magna Cum Laude
                    from California State University, Fullerton in 2023.
                  </p>
                </div>
                <div className="flex flex-col gap-4 min-[400px]:flex-row">
                  <Link
                    href="https://github.com/A-Hoblit"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Github
                  </Link>
                  <button
                    onClick={scrollToBottom}
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  >
                    Contact Me
                  </button>
                </div>
              </div>
              <Image
                src="https://utfs.io/f/sr1WqVUf52DPk32GLK6bqwNcJk4SxE7POgtLiQ3alUYW8oeV"
                width={600}
                height={600}
                alt="Andrew in Alaska"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover"
              />
            </div>
          </div>
        </section>
        <section
          id="projects"
          className="w-full bg-muted py-12 md:py-24 lg:py-32"
        >
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-6 text-center">
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Featured Projects
                </h2>
                <p className="max-w-[1000px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Check out some of my recent work. I've developed a variety of
                  projects, from image processors to full stack web
                  applications, all built with the latest technologies and best
                  practices.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-8 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <Image
                  src="https://utfs.io/f/sr1WqVUf52DP7oCsbLLtECmbs5yXoUaVkvIiuWgAZ32RwMfq"
                  width={550}
                  height={310}
                  alt="Edge Detection"
                  className="mx-auto overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                />
                <div className="grid gap-2">
                  <h3 className="text-xl font-bold">Edge Detection</h3>
                  <p className="text-muted-foreground">
                    My experiments with image processing in C++. This program
                    intakes an image and can produce a number of results from
                    color shifting, flipping, and edge detection using a matrix
                    convolution technique known as the Sobel Operator.
                  </p>
                  <div className="flex gap-4">
                    <Link
                      href="https://github.com/A-Hoblit/Image-Processing"
                      className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      GitHub
                    </Link>
                  </div>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <Image
                  src="https://utfs.io/f/sr1WqVUf52DPT0Do48s5McA3EzG4KjdShvrl98COseyWJYtq"
                  width={550}
                  height={310}
                  alt="Fluid Dynamics"
                  className="mx-auto overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                />
                <div className="grid gap-2">
                  <h3 className="text-xl font-bold">Physics Simulations</h3>
                  <p className="text-muted-foreground">
                    A set of physics simulations written in Python. I wanted to
                    learn different ways of demostrating data, and this project
                    uses both pygame and matplotlib for visualization, and numpy
                    to handle the calculations. The image shown is of the Fluid
                    Dynamics simulation.
                  </p>
                  <div className="flex gap-4">
                    <Link
                      href="https://github.com/A-Hoblit/Python-Physics-Simulations"
                      className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      GitHub
                    </Link>
                  </div>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <Image
                  src="https://utfs.io/f/sr1WqVUf52DP9TgyXr1vs8TmdCOSG6RJyfebNYFzMcKn2xZP"
                  width={550}
                  height={310}
                  alt="Image Gallery"
                  className="mx-auto overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                />
                <div className="grid gap-2">
                  <h3 className="text-xl font-bold">
                    Full Stack Image Gallery
                  </h3>
                  <p className="text-muted-foreground">
                    This is a full-stack, scalable image gallery based on the
                    serverless development style. It features authentication,
                    upload and scaling storage on a postgreSQL database, user
                    analytics, error tracking and rate limiting. Written in
                    typescript with Nextjs, React, and Tailwind to build the
                    front end.
                  </p>
                  <div className="flex gap-4">
                    <Link
                      href="https://github.com/A-Hoblit/imagegallery"
                      className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      GitHub
                    </Link>
                  </div>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <Image
                  src="https://utfs.io/f/sr1WqVUf52DPCLD0SrcF5FcvLWuht3lzYNgOqZfbGAwx6KIQ"
                  width={550}
                  height={310}
                  alt="Recipe Listing"
                  className="mx-auto overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                />
                <div className="grid gap-2">
                  <h3 className="text-xl font-bold">Recipe Applet</h3>
                  <p className="text-muted-foreground">
                    This project was my first experiments with web development.
                    Using standard javascript and React, this website features a
                    dynamically updating UI that changes based on what recipes
                    you have searched or saved.
                  </p>
                  <div className="flex gap-4">
                    <Link
                      href="https://github.com/A-Hoblit/Recipe-App"
                      className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      GitHub
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="skills" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-6 text-center">
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  My Skills
                </h2>
                <p className="max-w-[1000px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  As a software developer, I have a diverse set of skills that
                  allow me to tackle a wide range of development projects. I'm
                  proficient in multiple languages and many popular technologies
                  for web development, data analysis, and product management. I
                  am always eager to learn new frameworks and tools to improve
                  my ability.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-8 py-12 lg:grid-cols-3 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div className="flex items-center gap-2 rounded-lg bg-muted px-3 py-1">
                  <CodeIcon className="h-6 w-6" />
                  Languages
                </div>
                <ul className="grid gap-4">
                  <li className="flex items-center gap-2">
                    <PythonLogo className="h-6 w-6" />
                    <span>python</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CppLogo className="h-6 w-6" />
                    <span>C++</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <TypescriptLogo className="h-6 w-6" />
                    <span>Typescript</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <JavascriptLogo className="h-6 w-6" />
                    <span>Javascript</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <WebpageIcon className="h-6 w-6" />
                    <span>HTML / CSS</span>
                  </li>
                </ul>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <div className="flex items-center gap-2 rounded-lg bg-muted px-3 py-1">
                  <CodepenIcon className="h-6 w-6" />
                  Technologies
                </div>
                <ul className="grid gap-4">
                  <li className="flex items-center gap-2">
                    <ReactLogo className="h-6 w-6" />
                    <span>React</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <DatabaseIcon className="h-6 w-6" />
                    <span>SQL</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <NextjsLogo className="h-6 w-6" />
                    <span>Next.js</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <TailwindLogo className="h-6 w-6" />
                    <span>Tailwind CSS</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <NumpyLogo className="h-6 w-6" />
                    <span>numpy</span>
                  </li>
                </ul>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <div className="flex items-center gap-2 rounded-lg bg-muted px-3 py-1">
                  <FullscreenIcon className="h-6 w-6" />
                  Tools
                </div>
                <ul className="grid gap-4">
                  <li className="flex items-center gap-2">
                    <GitLogo className="h-6 w-6" />
                    <span>Git</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <GithubLogo className="h-6 w-6" />
                    <span>Github</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <VisualStudioLogo className="h-6 w-6" />
                    <span>Visual Studio</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <LinuxLogo className="h-6 w-6" />
                    <span>Linux</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <ApiIcon className="h-6 w-6" />
                    <span>APIs</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section
          id="contact"
          className="w-full border-t py-12 md:py-24 lg:py-32"
        >
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-6 text-center">
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Get in Touch
                </h2>
                <p className="max-w-[1000px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Feel free to reach out if you have any questions or would like
                  to collaborate on a project. I'm always excited to connect
                  with new people and explore new opportunities.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-4">
                <form
                  className="flex flex-col gap-4"
                  action="https://api.web3forms.com/submit"
                  method="POST"
                >
                  <input
                    type="hidden"
                    name="access_key"
                    value="1dcc4d91-297d-484d-ac28-d965d9bfc726"
                  ></input>
                  <input
                    type="hidden"
                    name="subject"
                    value="Submission from Portfolio"
                  ></input>
                  <input
                    type="checkbox"
                    name="botcheck"
                    className="hidden"
                  ></input>
                  <Input
                    type="text"
                    placeholder="Name"
                    name="First Name"
                    className="max-w-lg flex-1"
                  />
                  <Input
                    type="email"
                    placeholder="Email"
                    name="email"
                    className="max-w-lg flex-1"
                  />
                  <Textarea
                    placeholder="Message"
                    name="message"
                    className="max-w-lg"
                  />
                  <button
                    type="submit"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  >
                    Send
                  </button>
                </form>
              </div>
              <button
                onClick={scrollToTop}
                className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              >
                Back to the top
              </button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
